version: "3"
services:
  prometheus:
    image: rycus86/prometheus:2.7.1
    ports:
      - "9090:9090"
    volumes:
      - /home/jahn/shared/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/jahn/shared/prometheus/data:/prometheus  

  kafka-exporter:
    image: jahnestacado/prometheus-kafka-exporter-arm64v8 
    ports:
      - "9308:9308"
    command: ["--kafka.server=${HOST_IP:?HOST_IP must be set}:19092", "--kafka.server=${HOST_IP}:29092", "--kafka.server=${HOST_IP}:39092"]
    
  grafana:
    image: grafana/grafana:6.2.1
    user: 1000:1000
    ports:
      - "3000:3000"
    volumes:
      - /home/jahn/shared/grafana:/var/lib/grafana

  cadvisor:
    image: linuxkit/cadvisor:v0.6-arm64 
    hostname: '{{.Node.Hostname}}'
    deploy:
      mode: global
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

